---
apiVersion: v1
kind: Namespace
metadata:
  name: prometheus

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: carol
  namespace: prometheus

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: carol-cr
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "watch", "list"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: carol-crb
subjects:
- kind: Group
  name: system:serviceaccounts:prometheus
  namespace: prometheus
roleRef:
  kind: ClusterRole
  name: carol-cr
  apiGroup: rbac.authorization.k8s.io
  