apiVersion: v1 
kind: Pod 
metadata:
  name: web
  labels:
    key: app 
spec:
  containers: 
    - name: web
      image: mansory/web:version-2
      volumeMounts:
      - mountPath: /app
        name: app
      resources:
        requests:
          memory: "64Mi"
          cpu: "250m"
        limits:
          memory: "128Mi"
          cpu: "500m"
  initContainers:
    - name: page
      image: busybox:1.31.0
      command: ['sh', '-c', 'wget -O- https://tinyurl.com/otus-k8s-intro | sh']
      volumeMounts:
      - mountPath: /app
        name: app
  volumes:
    - name: app
      emptyDir: {}